app:
  build: .
  command: bash -l -c "bundle exec rails server -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
    - "80:80"
  links:
    - mysql
mysql:
  image: mysql
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: er_rental_development